env:
  global:
    - CONAN_REFERENCE: "appimageupdate/continuous"
    - CONAN_USERNAME: "appimage-conan-community"
    - CONAN_LOGIN_USERNAME: "azubieta"
    - CONAN_CHANNEL: "stable"
    - CONAN_UPLOAD: "https://api.bintray.com/conan/appimage-conan-community/public-conan"

notifications:
  email: false

linux: &linux
  os: linux
  dist: xenial
  sudo: required
  language: python
  python: "3.6"
  services:
    - docker

matrix:
  include:

    - <<: *linux
      env: CONAN_GCC_VERSIONS=4.8 CONAN_DOCKER_IMAGE=conanio/gcc48

    - <<: *linux
      env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=conanio/gcc7

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
